### PR TITLE
Update the gem search UI

### PR DESCRIPTION
**Pull request by Protuhj**
Added an autocomplete popup for the gem search box.
On 'Enter', the UI also scrolls now so the gem is visible. (This code is currently ugly)

Made it so the gem popup is only created once, and just closed/shown instead of closed and recreated.

### CODE REVIEW

**Comment by karakasis** [comment]
Hey, thanks for the work! I resolved a conflict that existed in dev branch, master is left behind atm. I haven't tried the code yet, but there appears to be an error. At method notePopup() , in MainApp_Controller
socketGroupGemPopup.setCacheContainer(true); , method setCacheContainer doesn't exist.

EDIT: On creating the dialogue now there is a 4-5 second lag. I commented the above line btw.
Other than this, it works really nice, great addition! Do you think you can make it also scroll the horizontal scroll bars, or even mark the gem icon itself, rathen than the whole quest panel?
EDIT2: There were some discussion about redesigning this particular UI from the scratch, with addition of gem tags that are now in the code. If you want to work on this let me know (future update)

**Comment by Protuhj** [comment]
It looks like you removed the lib/jfoenix-8.0.8.jar file, have you replaced/updated that library?

My machine has a maximum of 600 milliseconds of lag on creating the search UI, 4-5 seconds sounds huge. Is that higher or lower than prior to my changes?

**Comment by karakasis** [comment]
It's higher by a lot. It used to be ~600ms. Its not the lib, cause im using it for almost everything. Add me on Discord if you can rainy#1844

EDIT: It seems that the load time isn't stable. At first launch now im seeing 2-3 sec load , and then it drops to ~1sec. So it's not that big of deal. But maybe the line I commented can improve it, if I manage to find the method in the Lib.
EDIT 2: Im using jfoenix-8.0.7.jar
EDIT 3: Updating to 8.0.8 accepted the line, but im still getting ~1sec load times, but will have to do for now :) Thanks again awesome work man. If you are interested in reworking the whole UI at gem selection let me know.

**Comment by Protuhj** [comment]
You committed a file that was pointing to a local file on your hard drive.
I re-added the file and removed the commons-codec files since you were only using them to decode Base64, which is built into Java 8.

**Pull request merged**
